### ISSUE TITLE
Go 1.5.2

### ISSUE THREAD

**Issue by Anon-Penguin** [vieux/gocover.io#16]
Go 1.5.2 is out, but Gocover doesn't support it. Can you please add support for this (and maybe make it the default)? Thanks!

**Comment by vieux** [comment]
@Anon-Penguin done I added 1.5.3 and 1.6-rc1

**Comment by Anon-Penguin** [comment]
Thanks! Have a star! ⭐️

**Comment by yahelmanor** [comment]
Hello
The same problem was just created when I updated my software to GO 1.9, it would be nice if you could update the site again

**Comment by vieux** [comment]
@yahelmanor go1.9 is already the default on the site, what's you package ?
