### ISSUE TITLE
Badge URL redirects to GoCover.io homepage

### ISSUE THREAD

**Issue by jeevatkm** [vieux/gocover.io#17]
Hello - 

Badge URL http://gocover.io/_badge/github.com/go-resty/resty is getting redirected to gocover.io Homepage. Can you please have a look?

**Comment by vieux** [comment]
@jeevatkm yes I'm sorry I'm going o fix this asap, the http-> https redirection is broken, the best is to switch to `https://gocover.io/_badge/github.com/go-resty/resty`

But I'm going to fix for http.

**Comment by jeevatkm** [comment]
Thanks @vieux, I will use https for now.

**Comment by vieux** [comment]
It should be fixed (you might want to refresh your cache and/or try in a new browser)

But I would advise you to keep https.

**Comment by jeevatkm** [comment]
Okay, I will use https always. Thanks.
