### ISSUE TITLE
Need help - github markdown image display shows an error

### ISSUE THREAD

**Issue by jeevatkm** [vieux/gocover.io#20]
**Screenshot:**
<img width="629" alt="screen shot 2016-05-17 at 11 29 58 pm" src="https://cloud.githubusercontent.com/assets/1175977/15349412/618e508e-1c87-11e6-94b3-beee2bc43e79.png">

I'm able to access coverage badge image (https://gocover.io/_badge/github.com/go-resty/resty) via  browser. However it shows an error in the Github markdown readme.

**Markdown:**
[![GoCover](https://gocover.io/_badge/github.com/go-resty/resty)](https://gocover.io/github.com/go-resty/resty)

Any idea?

**Comment by jeevatkm** [comment]
@vieux - Any updates?

**Comment by jackspirou** [comment]
I am getting the same coverage error badge as well

**Comment by jeevatkm** [comment]
Thanks, never mind. I have pointed code coverage to [http://codecov.io](http://codecov.io/).

gocover.io was easy to use :)
