### ISSUE TITLE
gocover.io returns errors

### ISSUE THREAD

**Issue by codesenberg** [vieux/gocover.io#28]
Hi, @vieux!
First of all, thank you, for making this software, but recently I discovered that no matter which repo I try [gocover.io](http://gocover.io) returns following error:

> template: layout:66:7: executing "layout" at <yield>: error calling yield: html/template: "" is undefined

Try [this link](http://gocover.io/github.com/spf13/cobra) for example.

Badges show errors, too:

![badge](http://gocover.io/_badge/github.com/upsin/upsin)

**Comment by bwmarrin** [comment]
I've also had a problem where my badge shows this error.  It's happening right now, actually for this repo https://github.com/bwmarrin/go-alone

**Comment by codesenberg** [comment]
Everything seems to be working now.
I'll keep the issue open until tomorrow, just in case.

**Comment by vieux** [comment]
Yes, it seems to be working fine now, looks like a corruption in the redis Db I used, I'm investigating.

**Comment by codesenberg** [comment]
@vieux, guess I'll keep the issue open until you finish your investigation then.

**Comment by codesenberg** [comment]
@vieux, I'll have you know that this issue popped up again today.

**Comment by codesenberg** [comment]
@vieux, any updates on this? Service worked few days ago IRC, but now this issue is popping up again. Also, on a main page "Most popular repositories" and "Last repositories covered" were empty even when service worked.

**Comment by vieux** [comment]
@codesenberg my bad, it was an error in the redis config, should be good now, I'll monitor more closely

**Comment by codesenberg** [comment]
@vieux, :thumbsup:. I'll close this for now, since everything seem to be working fine.
