### ISSUE TITLE
"Last repositories covered" are not being updated and strange behaviour of badges

### ISSUE THREAD

**Issue by codesenberg** [vieux/gocover.io#29]
Few days ago I noticed that "Last repositories covered" are not being updated. They look like this now:

![Last repositories covered](http://i.imgur.com/3aspVEz.png)

Also, badges for new repos show "coverage error", see [here](https://gocover.io/_badge/github.com/alecthomas/kingpin), but work just fine for repos from "Last repositories covered", like [github.com/akmyazilim/assetmanager](https://gocover.io/_badge/github.com/akmyazilim/assetmanager).

Edit: uploaded pic to a different image host.

**Comment by vieux** [comment]
I can't see the picture, I'm not sure what you mean

**Comment by codesenberg** [comment]
> I can't see the picture

Superwierd. Like I said:
> "Last repositories covered" are not being updated

Go to [gocover.io](http://gocover.io/), look at the "Last repositories covered" block and you'll see:
* github.com/seefan/to
* github.com/akmyazilim/assetmanager
* github.com/rs/xhandler
* github.com/mafredri/cdp/cdptype

They have been there for a few days and if you run tests for some other repo it won't show up in this list. I suppose it's the same story for "Most popular repositories".

**Comment by codesenberg** [comment]
@vieux, well, the issue is gone now, because service was rebooted, but the bug is probably still there, so, leaving it open in case it pops up again.
