### ISSUE TITLE
badge

### ISSUE THREAD

**Issue by nathany** [vieux/gocover.io#3]
It would be awesome to have a coverage badge from gocover.io. /cc @espadrine

See https://github.com/badges

**Comment by nathany** [comment]
Afaik, the OAuth stuff is just required if you want to make it easy for the user to add a webhook from your site.

You could also just ask people to set it up by hand with a bit of documentation. From what I can tell the secret is optional, just need a url:

![webhook](https://cloud.githubusercontent.com/assets/4566/5690591/c8e5c6ca-9850-11e4-98bf-85038eb8ff38.png)

If there was a page/dialog with the markdown for a badge, it could easily contain the webhook url too. The badge url and payload url could be dynamic. It could also link to the page to set things up. https://github.com/{{user}}/{{repo}}/settings/hooks/new

The other end of the spectrum is something like Waffle.io, which doesn't only add a webhook via the API, they optionally open a pull request to add their badge. But for something that doesn't really need authorization, I think manual setup is fine for those who want it.

**Comment by nathany** [comment]
Maybe instead of "**87.2%**" in the top left, there could be the badge. 

![](https://img.shields.io/badge/coverage-87.2%-brightgreen.svg?style=flat)

Or is that view coming from Go's cover tool and difficult to customize?

Clicking the badge could bring up a page with the Markdown and Webhook instructions. This is what I went with for GoDoc (with lots of help from Gary Burd):
http://godoc.org/github.com/go-fsnotify/fsnotify?tools

Alternatively, Travis CI pops up a dialog box when clicking the badge.
https://travis-ci.org/go-fsnotify/fsnotify

**Comment by vieux** [comment]
we can definitly do it, it's added in go there: https://github.com/vieux/gocover.io/blob/master/server/server.go#L80

**Comment by hotei** [comment]
I was wondering what the status of this is on gocover.io.  I copied the badge html for github.com/PieterD/diff and it works, but when I substitute my own repo it fails.

**Comment by waterlink** [comment]
@hotei I think you need to manually run the coverage report first by visiting http://gocover.io/github.com/<user>/<repo> - only after that `_badge/<user>/<repo>` works.

**Comment by agnivade** [comment]
I am thinking of an approach like this. - Make a request to the http://gocover.io/github.com/<user>/<repo> url from travis after a push is completed. This should update the numbers automatically.
