### ISSUE TITLE
Go 1.9

### ISSUE THREAD

**Issue by treeder** [vieux/gocover.io#33]
Any chance you guys can update to 1.9?

**Comment by vieux** [comment]
Let me check, it should be already. might me a mistake on my side.

**Comment by vieux** [comment]
should we good now

**Comment by ckatsak** [comment]
Are you sure 1.9 is being used now?

I'm still getting a `t.Helper undefined (type *testing.T has no field or method Helper)` error, although the tests run fine on my local installation (1.9.2). A quick search for this error shows that it's usually the version being < 1.9 causing this.

**Comment by vieux** [comment]
my bad! it is now :/
