### ISSUE TITLE
Badges seems to be down

### ISSUE THREAD

**Issue by MichaelS11** [vieux/gocover.io#38]
Greetings,

Are badges not working? Does the server need to be restarted? Or is there something else going on?

I am trying the following:
https://gocover.io/_badge/github.com/MichaelS11/go-file-lock
https://gocover.io/_badge/github.com/MichaelS11/go-scheduler

**Comment by vieux** [comment]
@MichaelS11 my bad, fixed!

**Comment by MichaelS11** [comment]
@vieux
Thank you! :)
