### ISSUE TITLE
Badges seems to be down

### ISSUE THREAD

**Issue by MichaelS11** [vieux/gocover.io#39]
Greetings,

Are badges and the website seems to be having issues again. Any idea what keeps happening?

https://gocover.io/_badge/github.com/MichaelS11/go-file-lock
https://gocover.io/_badge/github.com/MichaelS11/go-scheduler

**Comment by MichaelS11** [comment]
@vieux 
Any thoughts?

**Comment by vieux** [comment]
Sorry, I'm off right now.

I restarted and it seems to be working, I'll investigate when I'm back

**Comment by MichaelS11** [comment]
Just FYI, for when you get back, doesn't seem to last very long. They seem to be down again.

**Comment by MichaelS11** [comment]
@vieux ,

Sill down :(

**Comment by MichaelS11** [comment]
Has been working as of late. @vieux did you figure out the issue?
