### ISSUE TITLE
wrong invocation of go test

### ISSUE THREAD

**Issue by torbenschinke** [vieux/gocover.io#42]
gocover.io invokes only *go test* instead of *go test./...*

This results in an entirely wrong coverage reporting, e.g. https://gocover.io/github.com/worldiety/errors
Actually this should report a coverage of 98,6% but reports 38,2%.

**Comment by vieux** [comment]
![screen shot 2019-01-03 at 11 54 20 am 1](https://user-images.githubusercontent.com/1032519/50658486-5d60c700-0f4e-11e9-8aa3-d0caf19c02d4.png)

GoCover was designed to test only packages, not all the sub packages in a repo. As you can see here, the pkg `github.com/worldiety/errors` is only indeed covered at 38.2%

But I'll add a way allowing it to test `./...` in the future

**Comment by tymonx** [comment]
This pull request add `./...` to the `go test` invocation: https://github.com/vieux/gocover.io/pull/49

It uses the `go tool cover -func coverage.out` command to get final coverage result.

**Comment by tymonx** [comment]
Related issue #15

**Comment by vieux** [comment]
thanks, I'll take a look and deploy later today
