### ISSUE TITLE
badge path

### ISSUE THREAD

**Issue by pjebs** [vieux/gocover.io#43]
what is the path to add a github badge for my repo using gocover.io?

**Comment by rocketlaunchr-cto** [comment]
[![GoCover](https://gocover.io/_badge/github.com/rocketlaunchr/remember-go)](https://gocover.io/github.com/rocketlaunchr/remember-go)

**Comment by pjebs** [comment]
```
[![GoCover](https://gocover.io/_badge/github.com/rocketlaunchr/remember-go)](https://gocover.io/github.com/rocketlaunchr/remember-go)
```
