### ISSUE TITLE
Docker customization

### ISSUE THREAD

**Issue by ozzono** [vieux/gocover.io#50]
Greetings,

Since the tests are executed within a docker container, is it possible to customize such container?

Best regards

**Comment by vieux** [comment]
Hi,

What do you mean by customize? No easy way to do it today, but if it's only missing one or two small libs, I can probably add them.

**Comment by ozzono** [comment]
Hi,

By customizing I mean some kind of Dockerfile detailing what is needed to test the package.
Due to network usage and build time it may be needed to add some kind of paywall.

Regards,
