### ISSUE TITLE
Update to Go 1.16

### ISSUE THREAD

**Issue by DarkFighterLuke** [vieux/gocover.io#51]
Hello, I think an update should be done to the available Go versions, because applications running on the latest specs cannot be tested at the moment (for example for the merging of `ioutils` into `os`).

**Comment by vieux** [comment]
@DarkFighterLuke sorry for the very slow answer. I updated to 1.16 but had to use `GO111MODULE=off` to make it work (will investigate removing it in the future)
What repo did you use to notice it wasn't working ?

**Comment by DarkFighterLuke** [comment]
Don't worry about the speed.

I was using https://github.com/NicoNex/echotron.

**Comment by vieux** [comment]
Seems to work fine, I'll close the ticket.
Thanks for the report.
