### ISSUE TITLE
Service is down

### ISSUE THREAD

**Issue by ncruces** [vieux/gocover.io#53]
Not sure if this is the correct place to report this, but [gocover.io](https://gocover.io) seems to be down.
The [HTTP](http://gocover.io) version spits out Caddy's welcome page.

**Comment by ncruces** [comment]
And, after being out for (I think?) a couple of days, it's now back 20min after I reported it.
If this nudged you into a fix, thanks, that was quick!
If it was just a fluke, please ignore this.

Thanks again!

**Comment by vieux** [comment]
Thanks a lot for the report, I'll improve monitoring.
