### ISSUE TITLE
Add current go version

### ISSUE THREAD

**Issue by yuri-norwood** [vieux/gocover.io#54]
Currently the versions are limited to v1.15 and v1.16, meaning that v1.17 modules don't work.

![image](https://user-images.githubusercontent.com/76186754/143944771-f7fe2971-8e52-41a9-8ebf-b0dcb7ffc995.png)

**Comment by ncruces** [comment]
Go 1.16 is out of support, so this would be a great time to update.

**Comment by twharmon** [comment]
GoCover is not working for me with Go 1.18. Am I missing something? Here is the link: [github.com/twharmon/dynago](https://gocover.io/github.com/twharmon/dynago).
