### ISSUE TITLE
Can't generate coverage for a package

### ISSUE THREAD

**Issue by yahavi** [vieux/gocover.io#55]
I'm trying to see test coverage for [github.com/jfrog/froggit-go](https://github.com/jfrog/froggit-go), but I'm getting an error:
![image](https://user-images.githubusercontent.com/11367982/147847133-9cd439e9-fc38-487d-a83a-0d2cd32b3d0e.png)

Here is the link to the report:
https://gocover.io/github.com/jfrog/froggit-go

The package is available in pkg.go.dev:
https://pkg.go.dev/github.com/jfrog/froggit-go

Thanks!

**Comment by francesconi** [comment]
Same for https://github.com/francesconi/go-rampart
