### ISSUE TITLE
Sad to see gocover.io go…

### ISSUE THREAD

**Issue by ncruces** [vieux/gocover.io#58]
Thanks for this, sad to see it go.

I created this tiny [script](https://github.com/ncruces/go-coverage-report/blob/main/coverage.sh) that you can run directly, or install as a [pre-commit](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) hook, to generate a badge and a coverage report.

You can see it in action in [`github.com/ncruces/go-sqlite3`](https://github.com/ncruces/go-sqlite3).

**Comment by vieux** [comment]
That's a good idea, I wonder if it could be turned into an github app. Could be a nice gocover.io replacement. (the website could point to the app)

**Comment by vieux** [comment]
On the one hand I like the idea of a separate branch, since it allows to easily keep track / see historical data, but it will make the repo "heavier", would take longer to clone. Probably the best would be to make it configurable ?

**Comment by ncruces** [comment]
I hadn't thought of the historical data, that's an interesting perspective.

A separate branch puts up those noisy warnings "blahrgh had recent merges, want to create a PR?" Only you see them, but they're annoying.

For GitHub, I think a single (private?) Gist that can hold badges for all your modules is probably the leanest option.
But it has some setup (creating the Gist, access tokens, etc).

I'd need to try.

**Comment by vieux** [comment]
I'd be happy to collaborate with you on this if you want to 😊

**Comment by ncruces** [comment]
Sure! 😀 Although I'll be away from the computer next week, so if you want to, run with it, it's just a simple script.

For me, the script already works well both manually and as a pre-commit hook. I'll clean it up, document it, and keep the Gist up to date. For the GitHub environment, an action would be interesting, for sure.

The main advantages of this vs. other solutions (IMO) are “self hosting” and actually showing the coverage report (just the badge is easier, of course). This requires saving those two files (SVG badge and HTML report) somewhere they can be fetched through HTTPS with a stable URL (that doesn't cause problems on GitHub README and pkg.go.dev). It should be noted that the HTML report includes an entire copy of your source code (can be large, has licensing implications).

I mentioned 4 solutions, but open to further suggestions:
1. in the repo, same branch
  - works as pre-commit, but adds a useless commit in the action
2. in the repo, bare branch
  - repo owner sees banners announcing the recent commit
3. in a public/private Gist
  - a copy of the entire source code goes to a Gist
  - further auth tokens needed?
4. in the wiki
  - I don't think this works for the HTML coverage file
5. …

No solution looks perfect, not sure which one is best, and making it very configurable goes against it being “one click.”

**Comment by ncruces** [comment]
It seems the wiki does work after all, and IMO is the best option.

I created a custom GitHub Action, which you can see in action on: [`github.com/ncruces/julianday`](https://github.com/ncruces/julianday)

Here is the code for the action (just uses the [script](https://gist.github.com/ncruces/0f3b9fa523dc823d4e642d38ea9ff06a) above):
https://github.com/ncruces/julianday/blob/main/.github/workflows/coverage.yml

Advantages of wiki:
- no banners to merge PRs
- no tokens needed (you already have the token needed to update the wiki)
- no copy of source code going elsewhere; just assume wiki is covered by same licence
- no content to see on the wiki (wiki resources are hidden, not browsable/discoverable)

Then the badge is applied to the README.md as such:
```markdown
[![Go Coverage](https://github.com/ncruces/julianday/wiki/coverage.svg)](https://raw.githack.com/wiki/ncruces/julianday/coverage.html)
```

I'll try to figure out how to publish it as an action.

**Comment by vieux** [comment]
That's really cool, well done! When I shut down the website, I'll link to `go-coverage-report` 👍

**Comment by vieux** [comment]
Updated the readme and website. Thanks again.
