### ISSUE TITLE
Enhancement: link to GitHub repo

### ISSUE THREAD

**Issue by nathany** [vieux/gocover.io#8]
It would be nice to include a link back to the code on GitHub.

**Comment by vieux** [comment]
I agree, right now it's only on http://gocover.io/about

**Comment by nathany** [comment]
For example, if I send a tweet like this:
https://twitter.com/gofsnotify/status/553791600736759808

Which links to:
http://gocover.io/github.com/go-fsnotify/fsnotify

There is no link back to:
https://github.com/go-fsnotify/fsnotify

**Comment by vieux** [comment]
Oh, I get it, very good idea.

**Comment by nathany** [comment]
Maybe an Octocat icon? http://zurb.com/playground/social-webicons#

**Comment by vieux** [comment]
yes, probably here
![screen shot 2015-01-09 at 22 51 51](https://cloud.githubusercontent.com/assets/1032519/5690707/40eaee7e-9852-11e4-8e09-6099a22567c4.png)

**Comment by nathany** [comment]
What do you think of breaking that header into two sections?

1. GoCover.io, Status, About
2. Linked GitHub repo url, Badge (#3), Tweet.

**Comment by vieux** [comment]
it seems a good idea

**Comment by nathany** [comment]
If I can run gocover locally on my Mac, I can give it a shot. Tomorrow I have a hackathon and need something to hack on.

**Comment by vieux** [comment]
Cool! it should be pretty easy ot run on mac, the only "complicated" part,
would be redis, but you can setup a free redislab account and it works


On Fri, Jan 9, 2015 at 11:06 PM, Nathan Youngman <notifications@github.com>
wrote:

> If I can run gocover locally on my Mac, I can give it a shot. Tomorrow I
> have a hackathon and need something to hack on.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vieux/gocover.io/issues/8#issuecomment-69446416>.
>



-- 
Victor Vieux
http://vieux.fr

**Comment by nathany** [comment]
Oh, I have redis from working on GoDoc. I thought Docker might be a bit complicated (boot2docker and all that).

**Comment by vieux** [comment]
oh right :D sorry docker is just a detail for me :D

On Fri, Jan 9, 2015 at 11:09 PM, Nathan Youngman <notifications@github.com>
wrote:

> Oh, I have redis from working on GoDoc. I thought Docker might be a bit
> complicated (boot2docker and all that).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vieux/gocover.io/issues/8#issuecomment-69446593>.
>



-- 
Victor Vieux
http://vieux.fr

**Comment by nathany** [comment]
:+1: I'll give it a shot.

**Comment by nathany** [comment]
I got it all running, but I haven't had much luck adding a second fixed navbar in Bootstrap.

Alternatively, modifying the topbar from gocover to include the repo and Twitter link. Looking more closely at the code, I'm thinking some preliminary work might help, either of:
* Making a repo template that renders things extracted from gocover. That would make it easier to add things like the Twitter code into a template
* Just forking gocover and getting it to render the way gocover.io wants. https://github.com/golang/tools/blob/master/cmd/cover/html.go

**Comment by vieux** [comment]
I don't get the first bullet point ?

Can you explain me how you see the topbar ? I'll give it a try.

**Comment by nathany** [comment]
Re: no. 1, basically to pull out things like coverage % and content into variables. Then render those into a repo template. It would make it easier to extend the template with more bits of HTML.

Split into two lines somehow, not sure exactly. Either with the Octocat or just the full url (since not all code need be on GitHub?). Maybe something like:

[github.com/go-fsnotify/fsnotify](github.com/go-fsnotify/fsnotify) | `[/fsnotify.go (92.9%)]` | ![](https://img.shields.io/badge/coverage-87.2%-brightgreen.svg?style=flat)  | [twitter]
not tracked no coverage low coverage * * * * * * * * high coverage

(with the badge coming in later)

**Comment by nathany** [comment]
With the GoDoc badge added to results pages, this link back to GitHub is indirectly solved.

Good enough. Thanks!
